### ISSUE TITLE
Support for "subdirectories"

### ISSUE THREAD

**Issue by ramirobg94** [cloudlena/s3manager#29]
Are there any plan to support "sub" buckets

Id like to manage the bucket like a filesystem with paths like this:

- Bucket/public/asset 

Thanks 
Happy to contribute

**Comment by brandonsturgeon** [comment]
+1

I was excited to set this app up for my organization, but we arrange our data by subdir, so we simply can't use it :(

**Comment by greenaussie** [comment]
+1

Buckets many objects with logs whose object keys are determined by something like / year / month / date / hour / minute
